/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    public JTextField getjTextFieldCPFC() {
        return jTextFieldCPFC;
    }

    public void setjTextFieldCPFC(JTextField jTextFieldCPFC) {
        this.jTextFieldCPFC = jTextFieldCPFC;
    }

    public JLabel getLblCPFC() {
        return lblCPFC;
    }

    public void setLblCPFC(JLabel lblCPFC) {
        this.lblCPFC = lblCPFC;
    }
    
    
    
    
    public JButton getBtCastrarC() {
        return btCastrarC;
    }

    public void setBtCastrarC(JButton btCastrarC) {
        this.btCastrarC = btCastrarC;
    }

    public JTextField getjTextFieldNomeC() {
        return jTextFieldNomeC;
    }

    public void setjTextFieldNomeC(JTextField jTextFieldNomeC) {
        this.jTextFieldNomeC = jTextFieldNomeC;
    }

    public JTextField getjTextFieldSenhaC() {
        return jTextFieldSenhaC;
    }

    public void setjTextFieldSenhaC(JTextField jTextFieldSenhaC) {
        this.jTextFieldSenhaC = jTextFieldSenhaC;
    }

    public JTextField getjTextFieldUsuarioC() {
        return jTextFieldUsuarioC;
    }

    public void setjTextFieldUsuarioC(JTextField jTextFieldUsuarioC) {
        this.jTextFieldUsuarioC = jTextFieldUsuarioC;
    }

    public JLabel getLblNomeC() {
        return lblNomeC;
    }

    public void setLblNomeC(JLabel lblNomeC) {
        this.lblNomeC = lblNomeC;
    }

    public JLabel getLblSenhaC() {
        return lblSenhaC;
    }

    public void setLblSenhaC(JLabel lblSenhaC) {
        this.lblSenhaC = lblSenhaC;
    }

    public JLabel getLblUsuarioC() {
        return lblUsuarioC;
    }

    public void setLblUsuarioC(JLabel lblUsuarioC) {
        this.lblUsuarioC = lblUsuarioC;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeC = new javax.swing.JLabel();
        jTextFieldNomeC = new javax.swing.JTextField();
        jTextFieldUsuarioC = new javax.swing.JTextField();
        lblUsuarioC = new javax.swing.JLabel();
        jTextFieldSenhaC = new javax.swing.JTextField();
        lblSenhaC = new javax.swing.JLabel();
        btCastrarC = new javax.swing.JButton();
        jTextFieldCPFC = new javax.swing.JTextField();
        lblCPFC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeC.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblNomeC.setText("NOME");

        jTextFieldNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCActionPerformed(evt);
            }
        });

        jTextFieldUsuarioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioCActionPerformed(evt);
            }
        });

        lblUsuarioC.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblUsuarioC.setText("USUARIO");

        jTextFieldSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaCActionPerformed(evt);
            }
        });

        lblSenhaC.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSenhaC.setText("SENHA");

        btCastrarC.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btCastrarC.setText("CADASTRAR");

        jTextFieldCPFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFCActionPerformed(evt);
            }
        });

        lblCPFC.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCPFC.setText("CPF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuarioC, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUsuarioC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCPFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCPFC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSenhaC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btCastrarC)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeC)
                    .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioC)
                    .addComponent(jTextFieldUsuarioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFC))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSenhaC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addComponent(btCastrarC)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCActionPerformed

    private void jTextFieldUsuarioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioCActionPerformed

    private void jTextFieldSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaCActionPerformed

    private void jTextFieldCPFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFCActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cadastro().setVisible(true);
//            }
//        });
//    }
//
//    void setvisible(boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCastrarC;
    private javax.swing.JTextField jTextFieldCPFC;
    private javax.swing.JTextField jTextFieldNomeC;
    private javax.swing.JTextField jTextFieldSenhaC;
    private javax.swing.JTextField jTextFieldUsuarioC;
    private javax.swing.JLabel lblCPFC;
    private javax.swing.JLabel lblNomeC;
    private javax.swing.JLabel lblSenhaC;
    private javax.swing.JLabel lblUsuarioC;
    // End of variables declaration//GEN-END:variables
}
